version: '3.7'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    volumes:
      - ./elasticsearch/certs:/usr/share/elasticsearch/config/certs
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ELASTICSEARCH_PASSWORD=1234
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.1
    volumes:
      - ./kibana/certs:/usr/share/kibana/config/certs
      - ./kibana/data:/usr/share/kibana/data
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=1234
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
